### ISSUE TITLE
# Evaluate the Trained Checkpoint on CALVIN is not work proferly; due to incompatibility between python libraries

### ISSUE THREAD

**Issue by hanbit-o** [Shua-Kang/TaKSIE#3]
Thank you for sharing your impressive work!

I'm having trouble with the installation.

When I run:
```
conda create -n taksie python=3.9
conda activate taksie
pip install -r requirements.txt
```

I get the following error:
```
ERROR: No matching distribution found for numpy==2.2.0
```

So, I changed the Python version from 3.9 to 3.10:
```
conda create -n taksie python=3.10
```
The installation completed successfully without errors.

Next, I ran the example:
```
python example_inference.py
```

However, another error occurred:
```
cannot import name 'cached_download' from 'huggingface_hub'
```

I removed `cached_download` from the import line in 
`/easy-diffusion/installer_files/env/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py`
by following: https://github.com/easydiffusion/easydiffusion/issues/1851#issuecomment-2425265522
```python
# from
from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
# to
from huggingface_hub import HfFolder, hf_hub_download, model_info
```

Another error appeared:
```
File "~/miniconda3/envs/taksie/lib/python3.10/site-packages/diffusers/schedulers/scheduling_unipc_multistep.py", line 179, in __init__
    self.timesteps = torch.from_numpy(timesteps)
RuntimeError: Numpy is not available
```

After upgrading torch from 1.31.1 to 2.7.1 following this: https://stackoverflow.com/a/79653978/28487671,
the error was fixed.

However, when I run [Evaluate the Trained Checkpoint on CALVIN](https://github.com/Shua-Kang/TaKSIE?tab=readme-ov-file#evaluate-the-trained-checkpoint-on-calvin),
the compatibility issues between Python libraries are overwhelming.

Could you provide more guidance on [Evaluate the Trained Checkpoint on CALVIN](https://github.com/Shua-Kang/TaKSIE?tab=readme-ov-file#evaluate-the-trained-checkpoint-on-calvin)?

**Comment by Shua-Kang** [comment]
I updated the requirements to use the old version of huggingface_hub and numpy. Could you try it again?

**Comment by hanbit-o** [comment]
Thank you for your response! 

I've successfully executed the `calvin-evaluation`, and I wanted to share the process along with the issues I encountered after following your instruction and their respective fixes:


1. **Issue:** 
   ```
   AttributeError: module 'scipy.linalg' has no attribute 'tril'
   ```
   **Fix:** Downgrade SciPy: 1.13.1 → 1.12.0
   ```
   pip install scipy==1.12.0
   ```

2. **Issue:** 
   ```
   Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version.; jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.; jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
   ```
   **Fix:** https://github.com/tensorflow/tensorflow/issues/60913#issuecomment-1707955579 
   ```
   pip install nvidia-cudnn-cu11==8.6.0.163
   ```

3. **Issue:** 
   ```
   ImportError: Error instantiating 'calvin_env.envs.play_table_env.PlayTableSimEnv': ...
   cannot import name 'gcd' from 'fractions' (~/miniconda3/envs/taksie_calvin/lib/python3.9/fractions.py)
   when loading module 'calvin_env.camera.tactile_sensor.TactileSensor'.
   ```
   **Fix:** https://stackoverflow.com/a/67508158/28487671
   ```
   conda install networkx=2.5
   ```

4. **Issue:** 
   ```
   AttributeError: Error instantiating 'calvin_env.envs.play_table_env.PlayTableSimEnv': Error instantiating 'calvin_env.camera.tactile_sensor.TactileSensor': 
   module 'numpy' has no attribute 'float'.
   ```
   **Fix:** Modify `urdf.py` at line 898:
   ```
   np.float --> np.float64
   ```

5. **Issue:** 
   `orbax.PyTreeCheckpointHandler(restore_with_serialized_types=False) encountered an unexpected keyword argument: 'restore_with_serialized_types'.`
   **Fix:** https://github.com/google/flax/issues/3417#issuecomment-2584958545 
   ```
   pip install orbax-checkpoint==0.4.1
   ```

6. **Issue:** 
   ```
   FileNotFoundError: [Errno 2] No such file or directory: '/scratch/qhv6ku/from_cs_server/generated_result_image_for_paper/for_evaluation/0_2_0.jpg'
   ```
   **Fix:** 
   - Create the directory: `~/TakSIE/scratch/qhv6ku/from_cs_server/generated_result_image_for_paper/for_evaluation`
   - Set path at `TaKSIE/taksie/taksie_wrapper.py: line 410` : 
   ```
   save_path_for_progress_evaluator = "~/TakSIE/scratch/qhv6ku/from_cs_server/generated_result_image_for_paper/for_evaluation"
   ```

Finally, everything is working now!

**Comment by Shua-Kang** [comment]
Thank you for sharing! I am surprised there are so many library issues. I'll update them later.
